from django.db import models

class Genre(models.Choices):
    ROCK = "Rock"
    POP = "Pop"
    JAZZ = "Jazz"
    BLUES = "Blues"
    HIP_HOP = "Hip-Hop"
    RAP = "Rap"
    CLASSICAL = "Classical"
    ELECTRONIC = "Electronic"
    HOUSE = "House"
    TECHNO = "Techno"
    METAL = "Metal"
    PUNK = "Punk"
    COUNTRY = "Country"
    REGGAE = "Reggae"
    FOLK = "Folk"
    RNB = "R&B"
    SOUL = "Soul"
    DISCO = "Disco"
    TRAP = "Trap"
    DRUM_AND_BASS = "Drum and Bass"
    INDIE = "Indie"
    LOFI = "Lo-fi"
    AMBIENT = "Ambient"
    SOUNDTRACK = "Soundtrack"