# Generated by Django 5.2.8 on 2025-12-01 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='genre',
            field=models.CharField(blank=True, choices=[('rock', 'Rock'), ('pop', 'Pop'), ('jazz', 'Jazz'), ('blues', 'Blues'), ('hip-hop', 'Hip-Hop'), ('rap', 'Rap'), ('classical', 'Classical'), ('electronic', 'Electronic'), ('house', 'House'), ('techno', 'Techno'), ('metal', 'Metal'), ('punk', 'Punk'), ('country', 'Country'), ('reggae', 'Reggae'), ('folk', 'Folk'), ('r&b', 'R&B'), ('soul', 'Soul'), ('disco', 'Disco'), ('trap', 'Trap'), ('drum and bass', 'Drum and Bass'), ('indie', 'Indie'), ('lo-fi', 'Lo-fi'), ('ambient', 'Ambient'), ('soundtrack', 'Soundtrack')], max_length=45, null=True),
        ),
    ]
