# Generated by Django 5.2.8 on 2025-12-01 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_name', models.CharField(max_length=128)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='private', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(limit_choices_to={'role': 'listener'}, on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('duration', models.PositiveIntegerField()),
                ('genre', models.CharField(choices=[('rock', 'Rock'), ('pop', 'Pop'), ('jazz', 'Jazz'), ('blues', 'Blues'), ('hip-hop', 'Hip-Hop'), ('rap', 'Rap'), ('classical', 'Classical'), ('electronic', 'Electronic'), ('house', 'House'), ('techno', 'Techno'), ('metal', 'Metal'), ('punk', 'Punk'), ('country', 'Country'), ('reggae', 'Reggae'), ('folk', 'Folk'), ('r&b', 'R&B'), ('soul', 'Soul'), ('disco', 'Disco'), ('trap', 'Trap'), ('drum and bass', 'Drum and Bass'), ('indie', 'Indie'), ('lo-fi', 'Lo-fi'), ('ambient', 'Ambient'), ('soundtrack', 'Soundtrack')], max_length=30)),
                ('release_date', models.DateTimeField(auto_now_add=True)),
                ('singer', models.ForeignKey(limit_choices_to={'role': 'singer'}, on_delete=django.db.models.deletion.CASCADE, related_name='songs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MusicEstimation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimation', models.CharField(choices=[('dislike', 'Дизлайк'), ('like', 'Лайк'), ('listen', 'Прослушан')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='musicestimations', to=settings.AUTH_USER_MODEL)),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.song')),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='music.playlist')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appearances', to='music.song')),
            ],
            options={
                'unique_together': {('playlist', 'song')},
            },
        ),
        migrations.CreateModel(
            name='SongEstimation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimation', models.CharField(choices=[('listened', 'Listened'), ('liked', 'Liked'), ('disliked', 'Disliked'), ('skipped', 'Skipped')], max_length=20)),
                ('listener', models.ForeignKey(limit_choices_to={'role': 'listener'}, on_delete=django.db.models.deletion.CASCADE, related_name='estimations', to=settings.AUTH_USER_MODEL)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimations', to='music.song')),
            ],
            options={
                'unique_together': {('listener', 'song')},
            },
        ),
    ]
